### ISSUE TITLE
Too many spaces after opening bracket

### ISSUE THREAD

**Issue by sjdaws** [phpfmt/php.tools#79]
We check our code with PHP Code Sniffer after it's checked in and it seems phpfmt doesn't remove empty lines after opening braces leading to the error: `Expected 1 newline after opening brace; 2 found`

This is caused by code like this:
```php
public function getName()
{
    if ($this->name) {

        return $this->name;
    }

    return '';
}
```

We've found it's mainly empty lines after if statements that cause the error. Is this something phpfmt can fix?

**Comment by Shaked** [comment]
Hey @sjdaws, I am very sorry for this bug. 

Would you mind sharing the phpfmt passes & configuration that you are using together with the php version? 

As well, if you don't mind, sharing the entire code and the phpcs command might help.

Thank you

**Comment by sjdaws** [comment]
Hi Shaked,

Thanks for getting back to me so quickly. I can't attach the file I was testing on but I've made up a file which throws the following errors that can't be resolved by phpfmt:

```
Lenny:Desktop scott$ phpcs --standard=ruleset.xml --tab-width=4 --report-full fmttest.php

FILE: /Users/scott/Desktop/fmttest.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 3 LINES
----------------------------------------------------------------------
 15 | ERROR | [x] Expected 1 newline after opening brace; 2 found
 26 | ERROR | [x] The CASE body must start on the line following the
    |       |     statement
 35 | ERROR | [x] The closing brace for the class must go on the next
    |       |     line after the body
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

Time: 15ms; Memory: 3.5Mb
```

This is my phpfmt.sublime-settings:
```
{
	"debug": true,
	"format_on_save": false,
	"passes":
	[
		"AlignDoubleArrow",
		"AlignDoubleSlashComments",
		"AutoPreincrement",
		"ClassToSelf",
		"DoubleToSingleQuote",
		"MergeElseIf",
		"PrettyPrintDocBlocks",
		"PSR2LnAfterNamespace",
		"ReturnNull",
		"SpaceBetweenMethods",
		"WrongConstructorName",
		"ReindentSwitchBlocks"
	],
	"php_bin": "/usr/local/bin/php",
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"version": 1
}
```

This is the failing php file:
```php
<?php

namespace Test;

class PhpFmtTest
{
    public function functionTest()
    {

        return 'FunctionTest';
    }

    public function ifTest()
    {
        if ($this->name == 'name') {

            return 'ifTestName';
        }

        return 'ifTest';
    }

    public function switchTest()
    {
        switch ($this->name) {
            case 'name':

                return 'switchTestName';
                break;
        }

        return 'switchTest';
    }

}
```

This is ruleset.xml for php code sniffer:
```xml
<?xml version="1.0"?>
<ruleset name="Rules">
    <description>Rules</description>
    <rule ref="PSR2">
        <exclude name="Generic.Files.LineEndings.InvalidEOLChar"/>
        <exclude name="PSR2.Classes.ClassDeclaration.SpaceAfterName"/>
        <exclude name="Generic.Files.LineLength.TooLong"/>
        <exclude name="PEAR.Functions.ValidDefaultValue.NotAtEnd"/>
        <exclude name="PSR1.Files.SideEffects.FoundWithSymbols"/>
        <exclude name="Generic.NamingConventions.UpperCaseConstantName.ConstantNotUpperCase"/>
        <exclude name="PSR1.Classes.ClassDeclaration.MissingNamespace"/>
        <exclude name="PSR1.Methods.CamelCapsMethodName.NotCamelCaps"/>
        <exclude name="PSR2.Classes.PropertyDeclaration.Underscore"/>
        <exclude name="PSR2.Methods.MethodDeclaration.Underscore"/>
        <exclude name="Squiz.Classes.ValidClassName.NotCamelCaps"/>
        <exclude name="Squiz.NamingConventions.ValidVariableName.NotCamelCaps"/>
        <exclude name="Squiz.NamingConventions.ValidVariableName.PublicHasUnderscore"/>
        <exclude name="Squiz.NamingConventions.ValidVariableName.StringNotCamelCaps"/>
    </rule>
</ruleset>
```

**Comment by ccirello** [comment]
@sjdaws Have you considered using `StripNewlineAfterClassOpen`, `StripNewlineAfterCurlyOpen` and `StripSpaceWithinControlStructures`?

**Comment by ccirello** [comment]
@Shaked I believe we might need extend `StripSpaceWithinControlStructures` to address the T_CASE.

**Comment by ccirello** [comment]
@Shaked worth checking 7a983e6b652bfc05c3d1d2cafed9225ae8b4bc32

**Comment by sjdaws** [comment]
@ccirello thanks for the prompt reply Carlos, I will check this first thing tomorrow. I assumed the newlines would be stripped by using --psr2 and must of missed the additional passes.

**Comment by Shaked** [comment]
Guys, just to make sure you know - I am on it.

**Comment by ccirello** [comment]
Gonna wait you to close this issue

**Comment by Shaked** [comment]
@ccirello didn't see you have fixed it :) closed

**Comment by sjdaws** [comment]
Hey guys, thanks heaps for pointing me towards the `strip` passes they seem to fix a bulk of the problem. I updated fmt.phar this morning and the case still has a blank space after it. Is there another pass to add?

**Comment by ccirello** [comment]
Share the other cases that are failing. Since 16.0.0 this should be solved.

**Comment by Shaked** [comment]
Hey @sjdaws, I have forgotten to update the phar in sublime text - now its updated, sorry for that. 

I copied your settings & code and added the 3 passes mentioned above by @ccirello. 

In case you are still experiencing issues, it would be great if you could share some more examples. 

This is my configuration from sublime text: 
```
{
	"debug": true,
	"format_on_save": true,
	"passes":
	[
		"AlignDoubleArrow",
		"AlignDoubleSlashComments",
		"AutoPreincrement",
		"ClassToSelf",
		"DoubleToSingleQuote",
		"MergeElseIf",
		"PrettyPrintDocBlocks",
		"PSR2LnAfterNamespace",
		"ReturnNull",
		"SpaceBetweenMethods",
		"WrongConstructorName",
		"ReindentSwitchBlocks",
		"StripNewlineAfterClassOpen",
		"StripNewlineAfterCurlyOpen",
		"StripSpaceWithinControlStructures"
	],
	"php_bin": "/usr/local/bin/php",
	"psr1": true,
	"psr1_naming": false,
	"psr2": true,
	"version": 1
}
```

and the result of `phpcs`:
```
Shaked@mac tmp $ phpcs --standard=ruleset.xml --tab-width=4 --report-full 1.php
Shaked@mac tmp $
```

**Comment by sjdaws** [comment]
Hi @Shaked and @ccirello, can confirm 16.0.0 did fix it now it's updated in sublime.

Thanks heaps for addressing it so quickly.

Scott.
