### ISSUE TITLE
Comments before T_IF

### ISSUE THREAD

**Issue by fabriziogiordano** [phpfmt/php.tools#92]
If there is a comment before a `T_IF` not add an extra line when `SpaceAroundControlStructures` is set.

### From
```php
//comment that explain the if
if (...) {
    //body
}
$someothercode...
```

### To
```php
//comment that explain the if
if (...) {
    //body
}

$someothercode...
```

**Comment by ccirello** [comment]
@Shaked Any insights?

**Comment by Shaked** [comment]
@fabriziogiordano @ccirello I am on it.

**Comment by Shaked** [comment]
Fixed including T_WHILE handling.

**Comment by ccirello** [comment]
I think the right fix is to add the space in the line before the first comment before the control structure. Not just skip it.

**Comment by Shaked** [comment]
I am not sure I am following, why?

**Comment by ccirello** [comment]
if you have this:

```
$b = foo();
if (...) {
    //body
}
```

you get this:
```
$b = foo();

if (...) {
    //body
}
```

but if you have this:
```
$b = foo();
// some comment
if (...) {
    //body
}
```

it does not fix to this:
but if you have this:
```
$b = foo();

// some comment
if (...) {
    //body
}
```

**Comment by Shaked** [comment]
I see your point. I didn't think about it. If I add a newline before the comment, it means that the ```// body``` comment will have a new line as well.. I guess I need to check if its not an empty line above it?

**Comment by ccirello** [comment]
You just need to memorize, when touching T_WHITESPACE, the number of line break, and act accordingly. You might need to inject a placeholder - or instead of appendCode, just update the $this->tkns with the extra line break, and re-render in the end. `render` is a bit slow, though.

**Comment by Shaked** [comment]
@ccirello so basically memorize the empty lines you mean?

**Comment by ccirello** [comment]
yeah.

**Comment by ccirello** [comment]
We'll keep working on this. @shaked do you can optimize this pass to avoid  the enormous amount of look aheads and backs?

**Comment by Shaked** [comment]
@ccirello yes

**Comment by Shaked** [comment]
@ccirello I guess it would be nice to find a way to skip:
```
!$this->leftUsefulTokenIs([T_OPEN_TAG]) &&
					$this->rightTokenIs([
						T_IF,
						T_DO,
						T_FOR,
						T_FOREACH,
						T_SWITCH,
						T_WHILE,
						T_COMMENT,
						T_DOC_COMMENT,
					])
```

Any ideas?

**Comment by ccirello** [comment]
I guess memorization might be the way to go. Take a look at the *memo* functions. I guess te best strategy is to implement both ways and break the tie through benchmark.
